In [16]:
# Create a Small Grid 
import gemmi as g
import numpy as np

np.random.seed(42)  # For reproducibility

grid = g.FloatGrid(1, 10, 10)
print("Grid Dimesions:", grid.nu, grid.nv, grid.nw )

# Fill the grid with random values
rand_vals = np.random.rand(grid.nu, grid.nv, grid.nw).round(2)
print(rand_vals[0, :, : ])

for i in range(grid.nu):
    for j in range(grid.nv):
        for k in range(grid.nw):
            grid.set_value(i, j, k, rand_vals[i, j, k])

# Print the grid values
print("Grid Values:")
matrix = grid.array
print(matrix[0, :, :])

Grid Dimesions: 1 10 10
[[0.37 0.95 0.73 0.6  0.16 0.16 0.06 0.87 0.6  0.71]
 [0.02 0.97 0.83 0.21 0.18 0.18 0.3  0.52 0.43 0.29]
 [0.61 0.14 0.29 0.37 0.46 0.79 0.2  0.51 0.59 0.05]
 [0.61 0.17 0.07 0.95 0.97 0.81 0.3  0.1  0.68 0.44]
 [0.12 0.5  0.03 0.91 0.26 0.66 0.31 0.52 0.55 0.18]
 [0.97 0.78 0.94 0.89 0.6  0.92 0.09 0.2  0.05 0.33]
 [0.39 0.27 0.83 0.36 0.28 0.54 0.14 0.8  0.07 0.99]
 [0.77 0.2  0.01 0.82 0.71 0.73 0.77 0.07 0.36 0.12]
 [0.86 0.62 0.33 0.06 0.31 0.33 0.73 0.64 0.89 0.47]
 [0.12 0.71 0.76 0.56 0.77 0.49 0.52 0.43 0.03 0.11]]
Grid Values:
[[0.37 0.95 0.73 0.6  0.16 0.16 0.06 0.87 0.6  0.71]
 [0.02 0.97 0.83 0.21 0.18 0.18 0.3  0.52 0.43 0.29]
 [0.61 0.14 0.29 0.37 0.46 0.79 0.2  0.51 0.59 0.05]
 [0.61 0.17 0.07 0.95 0.97 0.81 0.3  0.1  0.68 0.44]
 [0.12 0.5  0.03 0.91 0.26 0.66 0.31 0.52 0.55 0.18]
 [0.97 0.78 0.94 0.89 0.6  0.92 0.09 0.2  0.05 0.33]
 [0.39 0.27 0.83 0.36 0.28 0.54 0.14 0.8  0.07 0.99]
 [0.77 0.2  0.01 0.82 0.71 0.73 0.77 0.07 0.36 0.12]
 [0.86 0

In [23]:
# Look at a ccp4 grid
from pathlib import Path
ccp4Path = Path( "../../../data/s3Data/2017_lb18145-3/000-load/NUDT7A-x0140-event_2_1-BDC_0.14_map.native.ccp4" ).resolve().__str__()

map = g.read_ccp4_map(ccp4Path)
mapGrid = map.grid
print("CCP4 Map Grid Dimensions:", mapGrid.nu, mapGrid.nv, mapGrid.nw)
print("CCP4 Map Grid Unit Cell:", mapGrid.unit_cell)

mapArray = mapGrid.array
print("CCP4 Map Values (slice):")
print(mapArray[0, :, :].round(2))

CCP4 Map Grid Dimensions: 90 256 256
CCP4 Map Grid Unit Cell: <gemmi.UnitCell(125.882, 125.882, 41.66, 90, 90, 120)>
CCP4 Map Values (slice):
[[ 0.    0.    0.   ...  0.    0.    0.  ]
 [ 0.    0.    0.   ...  0.    0.    0.  ]
 [ 0.    0.    0.   ...  0.    0.    0.  ]
 ...
 [ 0.36  0.57  0.29 ... -0.14  0.39  0.6 ]
 [ 0.15  0.6   0.71 ... -0.36 -0.12  0.38]
 [ 0.22  0.35  0.72 ... -0.23 -0.38 -0.13]]
